### ISSUE TITLE
You can Help me to install? I pay

### ISSUE THREAD

**Issue by lukinhanw** [zGrav/xtream-iptv-player-reactnative#6]
You can Help me to install? I pay

**Comment by zGrav** [comment]
Everything is in the README, the hint is pretty explicit.

Feel free: https://www.paypal.me/therealzGrav and also view this one if interested https://github.com/zGrav/xtream-iptv-player-v3

**Comment by lukinhanw** [comment]
How price to send you ?

**Comment by zGrav** [comment]
@lukinhanw you send how much you feel like I deserve, I cannot put a price for you
