### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by LiamKenyon** [zGrav/xtream-iptv-player-reactnative#7]
First of all thanks for the source it’s been fun playing about with it.

Still yet to get it fully working as I’m assuming it’s a old crna format so will need migrated.

Either that or I’ve been doing something wrong haha.

**Comment by zGrav** [comment]
Hey my dude,

Not entirely sure what you mean by old crna/migration, since I ejected this app and it's purely handled through Expo and Android Studio/XCode :D

**Comment by LiamKenyon** [comment]
Ah probably just being an rtard. 

Will keep playing about with it sure will get it working sooner or later!
